// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WUWA_WINFORMS_POSTGRE;

#nullable disable

namespace WUWA_EF_CORE_Console.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002182145_AddTalants_2")]
    partial class AddTalants_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WUWA_CHARACTER_OOP.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("ElementId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RarityId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId");

                    b.HasIndex("ElementId");

                    b.HasIndex("RarityId");

                    b.HasIndex("RoleId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("WUWA_CHARACTER_OOP.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkillId"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TalantId")
                        .HasColumnType("integer");

                    b.HasKey("SkillId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("TalantId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("WUWA_CHARACTER_OOP.Models.Talant", b =>
                {
                    b.Property<int>("TalantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TalantId"));

                    b.Property<string>("TalantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TalantId");

                    b.ToTable("Talants");
                });

            modelBuilder.Entity("WUWA_WINFORMS_POSTGRE.Element", b =>
                {
                    b.Property<int>("ElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ElementId"));

                    b.Property<string>("ElementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ElementId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("WUWA_WINFORMS_POSTGRE.Models.Rarity", b =>
                {
                    b.Property<int>("RarityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RarityId"));

                    b.Property<string>("RarityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RarityId");

                    b.ToTable("Rarity");
                });

            modelBuilder.Entity("WUWA_WINFORMS_POSTGRE.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WUWA_WINFORMS_POSTGRE.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeaponId"));

                    b.Property<string>("WeaponName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WeaponId");

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("WUWA_CHARACTER_OOP.Models.Character", b =>
                {
                    b.HasOne("WUWA_WINFORMS_POSTGRE.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WUWA_WINFORMS_POSTGRE.Models.Rarity", "Rarity")
                        .WithMany()
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WUWA_WINFORMS_POSTGRE.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WUWA_WINFORMS_POSTGRE.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Rarity");

                    b.Navigation("Role");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("WUWA_CHARACTER_OOP.Models.Skill", b =>
                {
                    b.HasOne("WUWA_CHARACTER_OOP.Models.Character", null)
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WUWA_CHARACTER_OOP.Models.Talant", null)
                        .WithMany("Skills")
                        .HasForeignKey("TalantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WUWA_CHARACTER_OOP.Models.Character", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("WUWA_CHARACTER_OOP.Models.Talant", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
